services:
  book_catalog:
    image: book_catalog:latest
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: book_catalog_cntr
    ports:
     - "4000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit_722_part3_wfaa_user:wRB1C5x1wov2Oax7NSDGawBEHXr6WZqb@dpg-cs3omr56l47c73dame8g-a.oregon-postgres.render.com/sit_722_part3_wfaa
    restart: "no"

  inventory_management:
    image: inventory_management:latest
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: inventory_management_cntr
    ports:
     - "3000:7000"
    environment:
      - PORT=7000
      - DATABASE_URL=postgresql://sit_722_part3_wfaa_user:wRB1C5x1wov2Oax7NSDGawBEHXr6WZqb@dpg-cs3omr56l47c73dame8g-a.oregon-postgres.render.com/sit_722_part3_wfaa
    restart: "no"
