apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:  
        - name: book-catalog
          image: sit722part3.azurecr.io/book_catalog_az5:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              value: postgresql://sit_722_part3_wfaa_user:wRB1C5x1wov2Oax7NSDGawBEHXr6WZqb@dpg-cs3omr56l47c73dame8g-a.oregon-postgres.render.com/sit_722_part3_wfaa

---

apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 8000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:  
      - name: inventory-management
        image: sit722part3.azurecr.io/inventory_management_az5:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DATABASE_URL
          value: postgresql://sit_722_part3_wfaa_user:wRB1C5x1wov2Oax7NSDGawBEHXr6WZqb@dpg-cs3omr56l47c73dame8g-a.oregon-postgres.render.com/sit_722_part3_wfaa

apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 7000
